### ISSUE TITLE
Clean up getInstance()

### ISSUE THREAD

**Issue by johnnyfreeman** [johnnyfreeman/coseva#9]
The experience of getting an instance should be consistent whether you're using `new CSV` or `getInstance`. I think the following should be moved to the constructor.

``` php
// Resolve the path, so there is a better likelihood of finding a match.
$path = realpath($filename);

if (!$path) throw new InvalidArgumentException(
  'The fiven filename could not be resolved. Tried resolving '
  . var_export($filename, true)
);

$filename = $path;
```

And obviously fix the spelling error while we're at it. :P

**Comment by janmartenjongerius** [comment]
If you want consistency between `getInstance` and `__construct`, we should add the remaining parameters of `__construct` to `getInstance` as well. I do suggest you do not remove this logic from `getInstance`. At most, copy it, because we want instances to have a better likelihood of finding a match. _points at top most comment_

If you insist on adding this logic to the constructor, preventing double logic could be done by adding a private method `_resolvePath` which in turn can throw an `Exception`. You can either let that bubble up or catch that and rethrow it with a proper `InvalidArgumentException`.

**Comment by johnnyfreeman** [comment]
> we should add the remaining parameters of __construct to getInstance as well.

I totally agree. :)

> I do suggest you do not remove this logic from getInstance. At most, copy it, because we want instances to have a better likelihood of finding a match. points at top most comment

Maybe I'm just not thinking about this correctly (it happens), so correct me if I'm wrong. It's the job of `getInstance` to get an existing instance, or to delegate the creation of a new instance to the constructor if no previous instance exists. So the constructor will only be called once for the same file, but `getInstance` can be called any number of times. And since we only need to verify that the file and path are correct just once, and not every time we retrieve the instance, I think that any path/file checking should be done in the constructor.

``` php
$my_csv = Coseva\CSV::getInstance('my_csv.csv');

// in another scope somewhere
$my_csv = Coseva\CSV::getInstance('my_csv.csv');
```

I would hope that the code above would only check the path/file only once, since there is no reason to check it again as it's not being moved or copied anywhere, but especially if it's been parsed already as the `parse()` method now removes the reference to the file once it's been parsed the first time.

> preventing double logic could be done by adding a private method _resolvePath which in turn can throw an Exception. You can either let that bubble up or catch that and rethrow it with a proper InvalidArgumentException.

Since we won't need to resolve the path more than once for any single file, I think we should avoid extracting that logic to another method and leave all the path resolution in the constructor.

I'm I just not thinking this thing through well enough? Or what do you think? I have that feeling that i'm just missing something. :/

**Comment by johnnyfreeman** [comment]
Oh man, I see what you are doing now. You are using `realpath` to make the instance key more unique and more accurate. For some reason I was thinking you were _just_ checking if the path/file exists. Silly me. :P

Now that I see what's going on here, let me think about this some more...

**Comment by johnnyfreeman** [comment]
I still don't like that there is a file/path existence check on every instance lookup...

> realpath() returns FALSE on failure, e.g. if the file does not exist. 
> ~ http://www.php.net/manual/en/function.realpath.php

Maybe one of us will come up with better solution eventually. :D

For now, It's still a good idea to add the other two parameters to `getInstance()` and fix the spelling error.

**Comment by janmartenjongerius** [comment]
I will rethink processing the filename, since the current implementation of `__construct` and `getInstance` actually prevent checking the include path. I think it's a good idea to strip out the filename check from `getInstance` as users simply should suffer the consequences when entering different file names for the same source. They can do a realpath check themselves if they need to do so and we could actually add proper instructions for that.

I do think it's worth taking a look at combining the open mode and filename to create a key for the instances.

For the constructor, I'll be writing some logic that can check the current include paths for PHP. I do feel we should only do that if the given filename is using a relative path.
